### ISSUE TITLE
Feature request: a keystroke to clear

### ISSUE THREAD

**Issue by OldWartHog** [huoguangjin/MultiHighlight#1]
I've used this plugin for a little while and like it a lot.  One small additional feature would be nice - the ability to clear all highlights from the current file.  Typically when looking at a problem I add various highlights but when I have fixed the issue and want to look at some other issue I still have the old highlights.  I take remove them one by one but this is a bit tedious, so a clear all highlights would be good.

I also changed my colors to avoid red since this leads to confusion in the right hand gutter with syntax errors.

**Comment by huoguangjin** [comment]
@OldWartHog thank you for your appreciation.

Highlights belong to one editor(tab), [MultiHighlightClearAction](https://github.com/huoguangjin/MultiHighlight/commit/2db5761c091aed35f97bf836f59095a4b316aa96) is used to clear all highlights in current editor, you can add a shortcut to it.

![keystroke](https://github.com/huoguangjin/MultiHighlight/blob/dev/screenshot/keymap.png?raw=true)

New version is still under approve, but you can install from [MultiHighlight-1.0.1](https://github.com/huoguangjin/MultiHighlight/releases/tag/1.0.1) 😃
It is a little busy these days, sorry for the late replay.
