### ISSUE TITLE
Incompatible with AndroidStudio 4.2 release build

### ISSUE THREAD

**Issue by EvgenySamarin** [huoguangjin/MultiHighlight#22]
![image](https://user-images.githubusercontent.com/36430830/119351724-78f8d380-bca9-11eb-8323-c193380a31ae.png)

Android Studio 4.2.1
Build #AI-202.7660.26.42.7351085, built on May 10, 2021
Runtime version: 11.0.8+10-b944.6842174 amd64
VM: OpenJDK 64-Bit Server VM by N/A
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 12
Registry: external.system.auto.import.disabled=true, debugger.watches.in.variables=false
Non-Bundled Plugins: BashSupport, PlantUML integration, call-graph, com.intellij.plugins.gnomekeymap, com.intellij.plugins.xwinkeymap, com.intellij.jira, com.vermouthx.idea, org.jetbrains.kotlin, izhangzhihao.rainbow.brackets

**Comment by byunlee** [comment]
I also came to see why this plugin was not working in latest Android Studio

**Comment by huoguangjin** [comment]
to be fixed this weekend :ok_hand:

**Comment by EvgenySamarin** [comment]
very much looking forward to fixes, your product is my favorite tool in development, very sad that i can't use it yet 😢

**Comment by huoguangjin** [comment]
working in progress..

**Comment by huoguangjin** [comment]
fixed!

**Comment by huoguangjin** [comment]
New release is under approval.
Please install from [here v2.2.0-beta](https://github.com/huoguangjin/MultiHighlight/releases/tag/v2.2.0-beta) on AndroidStudio 4.2.

**Comment by byunlee** [comment]
@huoguangjin Thanks a lot. Using the ZIP file and the plugin is working great again.
