### ISSUE TITLE
feature request: highlight not only a word, but the whole line

### ISSUE THREAD

**Issue by roeniss** [huoguangjin/MultiHighlight#25]
something like this: https://chrome.google.com/webstore/detail/weava-highlighter-pdf-web/cbnaodkpfinfiipjblikofhlhlcickei?hl=en

Would it possible?

**Comment by roeniss** [comment]
or like this: https://marketplace.visualstudio.com/items?itemName=matthewhazlehurst.line-highlighter

**Comment by hiei17** [comment]
我也想要在功能!!!

**Comment by huoguangjin** [comment]
feature: highlight with plain text

**Comment by huoguangjin** [comment]
try [v3.0.0](https://github.com/huoguangjin/MultiHighlight/releases/tag/v3.0.0)
