### ISSUE TITLE
'null' highlighted in c# files in Rider

### ISSUE THREAD

**Issue by r-o-i** [huoguangjin/MultiHighlight#26]
When pressing the MultiHighlight hotkey...

### A) C# file in Rider:

-   First press: the word **null** is highlighted instead of my selected word.
-   Second press: my selected word is also highlighted.
-   Third press: **null** is un-highlighted.
-   Fourth press: my selected word is un-highlighted.
-   Fifth press: (cycle repeats with different colours)

![rider](https://user-images.githubusercontent.com/87650975/148866305-919c51df-8cab-46c0-9166-e6871de13650.gif)

### B) C# (or other) file in IntelliJ, or a non-C# file in Rider:

-   First press: my selected word is highlighted.
-   Second press: my selected word is un-highlighted.
-   Third press: (cycle repeats with different colours)

![intelliJ](https://user-images.githubusercontent.com/87650975/148866299-f363093a-d506-45ea-ae5c-edc85347f04c.gif)

### Expected behaviour is (B), not (A)

Using Rider v2021.3.2, MultiHighlight v2.1.1

**Comment by huoguangjin** [comment]
Rider is not supported yet, it is much different from intellij platform. see #8

**Comment by r-o-i** [comment]
My bad - I should have read the docs more carefully 😄 

Despite this, it does kind of work in Rider: the workaround is to use 3 click instead of 1.
