### ISSUE TITLE
should not match word with regex

### ISSUE THREAD

**Issue by sunznx** [huoguangjin/MultiHighlight#27]
match something like `[xxx]` will fail
<img width="168" alt="image" src="https://user-images.githubusercontent.com/8629792/156910317-fa1881c4-856c-4c79-8aa5-ceeeb341334e.png">

**Comment by huoguangjin** [comment]
feature: highlight with plain text

**Comment by huoguangjin** [comment]
try [v3.0.0](https://github.com/huoguangjin/MultiHighlight/releases/tag/v3.0.0)
