### ISSUE TITLE
Choose a color on highlight

### ISSUE THREAD

**Issue by michalovjan** [huoguangjin/MultiHighlight#32]
Hi!
Is there a possibility for feature to simply choose the highlight color on highlighting?

I have a vague idea how this could work. On keybinding( probably new one like cmd+\ ), you would get a popup with a list of available colors ordered as in settings and you could use additional keystroke like a number from 1-9 to select a color from keyboard or simply just select with mouse.

It would be super useful because sometimes I want to split my code into 2 or 3 parts and it's hard to do with cycling colors.

**Comment by huoguangjin** [comment]
I see. It is a nice feature which I really want too.
The popup UI for selecting colors could be like the Mnemonic Bookmark.

![Add Mnemonic Bookmark](https://user-images.githubusercontent.com/22366182/225511988-fbfe9b10-b8e0-4b65-82fe-e801134990a4.png)

**Comment by michalovjan** [comment]
That would be super awesome.

**Comment by huoguangjin** [comment]
# Different style of options list

- add mnemonic bookmark
com.intellij.ide.bookmark.actions.ChooseBookmarkTypeAction
com.intellij.ide.bookmark.actions.BookmarkTypeChooser
![Add Mnemonic Bookmark](https://user-images.githubusercontent.com/22366182/225511988-fbfe9b10-b8e0-4b65-82fe-e801134990a4.png)

- show intentions
com.intellij.codeInsight.intention.actions.ShowIntentionActionsAction
com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler
com.intellij.codeInsight.intention.impl.IntentionHintComponent
    <img width="559" alt="show intentions" src="https://user-images.githubusercontent.com/22366182/235350683-2bb33bc1-63e1-45a2-b5d8-33a7dc126acb.png">

- file stucture
com.intellij.ide.actions.ViewStructureAction
com.intellij.ide.util.FileStructurePopup
    <img width="597" alt="file stucture" src="https://user-images.githubusercontent.com/22366182/235351313-996e4ea8-ff4f-4ce8-878b-dae073f2bdd7.png">

- run
com.intellij.execution.actions.ChooseRunConfigurationPopupAction
com.intellij.execution.actions.ChooseRunConfigurationPopup
    <img width="315" alt="run" src="https://user-images.githubusercontent.com/22366182/235351799-c61d67fe-1d53-459c-a3b4-5e4c6de1fbe7.png">

- show line bookmarks
com.intellij.ide.bookmark.actions.ShowLineBookmarksAction
com.intellij.ide.bookmark.ui.BookmarksView
    <img width="803" alt="show line bookmarks" src="https://user-images.githubusercontent.com/22366182/235351953-2c25e761-24b9-46fd-b0cd-66c23fbaae66.png">

- basic (completion)
com.intellij.codeInsight.completion.actions.CodeCompletionAction
com.intellij.codeInsight.completion.CodeCompletionHandlerBase
com.intellij.codeInsight.lookup.impl.LookupManagerImpl
com.intellij.codeInsight.lookup.impl.LookupUi
    <img width="672" alt="basic" src="https://user-images.githubusercontent.com/22366182/235352276-ec54cc00-c059-4dbb-931a-dab275ff3a94.png">

**Comment by huoguangjin** [comment]
Feature implemented.
[Version 3.1.0](https://github.com/huoguangjin/MultiHighlight/tree/v3.1.0#highlight-with-specified-color) has been uploaded to the plugin marketplace and is now under review, it will be approved within two days if it goes well.

If you cannot wait to have a try, you can still install from [Release](https://github.com/huoguangjin/MultiHighlight/releases/tag/v3.1.0).

![highlight with specified color](https://raw.githubusercontent.com/huoguangjin/MultiHighlight/v3.1.0/screenshot/feature-specified-color.gif)

**Comment by michalovjan** [comment]
thank you very much @huoguangjin!
