### ISSUE TITLE
高亮未能区分：大小写+整个单词

### ISSUE THREAD

**Issue by AlanAnonymous** [huoguangjin/MultiHighlight#35]
例如我高亮A这个字符，但是a和AB和ba都被同时高亮了

能不能加个开关或者加这两个功能：
1. 区分大小写
2. 整词匹配

类似IDEA中的搜索栏的 Cc(Match case) 和 W(Words)
![image](https://github.com/huoguangjin/MultiHighlight/assets/47346564/127de19d-37e1-4322-bf16-f2f953a55a73)

**Comment by huoguangjin** [comment]
Same feature requests. #36 #37

**Comment by huoguangjin** [comment]
Try [v3.2.0](https://github.com/huoguangjin/MultiHighlight/releases/tag/v3.2.0)
