### ISSUE TITLE
Make highlight case sensitive

### ISSUE THREAD

**Issue by xxxxxxbox** [huoguangjin/MultiHighlight#36]
**Please consider making highlight case sensitive.**

foo and Foo in python are not the same things.

For example. I'd like to highlight custom class "Request". I've got only a couple of this word in my code. But when I try to do so, MultiHighlight highlight "request" word also. So, I get hundred highlighted words Request/request instead of two.

**Comment by huoguangjin** [comment]
Try [v3.2.0](https://github.com/huoguangjin/MultiHighlight/releases/tag/v3.2.0)
