### ISSUE TITLE
Option to select whole words only

### ISSUE THREAD

**Issue by xxxxxxbox** [huoguangjin/MultiHighlight#37]
Please consider adding option to select only whole words.

For example. I'd like to highlight whole word "request" but not higlight "_dump_request" etc.

```
Class Foo (request: Bar):
        data = self._dump_request(request)
        json_data = self._json_request(request)
        baz.request = data
        ...
```

**Comment by huoguangjin** [comment]
Try [v3.2.0](https://github.com/huoguangjin/MultiHighlight/releases/tag/v3.2.0)
