### ISSUE TITLE
怎么取消着色?

### ISSUE THREAD

**Issue by zhanggang807** [huoguangjin/MultiHighlight#5]

**Comment by huoguangjin** [comment]
可以这么做：

1. 光标放在原来高亮的地方再触发一次MultiHighlight，原来的高亮会被清除
2. 触发MultiHighlightClearAction，会清除当前editor的所有高亮
3. 关闭editor，会清除当前editor的所有高亮
4. 删除当前行，高亮会被清除

**Comment by zhanggang807** [comment]
够详细，赞~~
