### ISSUE TITLE
clear and toggle is not working in GoLand 2018.2.1

### ISSUE THREAD

**Issue by bloomTesla** [huoguangjin/MultiHighlight#7]
This plugin is very useful but I cannot clear the highlights.  I changed shortcuts to clear and toggle but it is still not working. Please check it.

**Comment by huoguangjin** [comment]
Thank you for your feedback!
Sorry for late reply.. (busy these days 😵)
I don't use GoLand very often, but I will take time to fix it. (maybe weekend..)
Is there any plugin errors reported by GoLand while using, Could you please provide more infomation?

**Comment by huoguangjin** [comment]
It works fine in GoLand 2018.3 (Build #Go-183.4284.141, built on November 21, 2018)
